{"name": "test_countNoMeasure", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <NewMeasure_test.NewTest testMethod=test_countNoMeasure>\n\n    @allure.testcase(\"Validate measure count with invalid measure\")\n    @allure.description(\"\")\n    @pytest.mark.flaky(reruns=2, reruns_delay=5)\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_countNoMeasure(self):\n        self.lp.login(user_data['username'], user_data['password'])\n        result = self.lp.verifyLoginSuccessful()\n>       self.ts.markFinal(\"test_validLogin\", result, \"Login was successful\")\n\nNewMeasure_test.py:99: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utilities.teststatus.TestStatus object at 0x10d8287f0>\ntestName = 'test_validLogin', result = False\nresultMessage = 'Login was successful'\n\n    def markFinal(self, testName, result, resultMessage):\n        \"\"\"\n        Mark the final result of the verification point in a test case\n        This needs to be called at least once in a test case\n        This should be final test status of the test case\n        \"\"\"\n        self.setResult(result, resultMessage)\n    \n        if \"FAIL\" in self.resultList:\n            self.log.error(testName +  \" ### TEST FAILED\")\n            self.resultList.clear()\n>           assert True == False\nE           AssertionError\n\n../../utilities/teststatus.py:63: AssertionError"}, "attachments": [{"name": "log", "source": "1c06f813-4c61-4cd2-af50-3058fe50d674-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "7891c48c-7866-401b-99ec-c0702282198b-attachment.txt", "type": "text/plain"}], "start": 1596557087227, "stop": 1596557104679, "uuid": "610ff45f-759f-4618-8442-428d5158efdf", "historyId": "f63c326dc31053968bafadf4bd30ef73", "testCaseId": "b0e4808b382e3ea96ef5d87bd551573b", "fullName": "NewMeasure_test.NewTest#test_countNoMeasure", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "flaky(reruns=2, reruns_delay=5)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('oneTimeSetUp', 'setUp')"}, {"name": "suite", "value": "NewMeasure_test"}, {"name": "subSuite", "value": "NewTest"}, {"name": "host", "value": "RRD023829463.tenethealth.net"}, {"name": "thread", "value": "5729-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "NewMeasure_test"}], "links": [{"type": "test_case", "url": "Validate measure count with invalid measure", "name": "Validate measure count with invalid measure"}]}